In [1]:
# Basic numpy array
import numpy as np
ar = np.zeros((2,3),dtype=np.float64)
print(ar,'\n')
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(ar.size,ar.nbytes,ar.ndim,ar.shape))

[[0. 0. 0.]
 [0. 0. 0.]] 

metadata : size=6, bytes=48, dim=2, shape=(2, 3)


In [2]:
# Reshape (copies data)
x = np.arange(1,13,1)
y = np.reshape(x,(2,2,3))
print(y,'\n')
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(y.size,y.nbytes,y.ndim,y.shape),'\n')
print("id(x)={0}, id(y)={1}".format(id(x),id(y)),'\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

metadata : size=12, bytes=48, dim=3, shape=(2, 2, 3) 

id(x)=2653557785904, id(y)=2653557786624 



In [3]:
# View (does not copy)
z = y[0,:,:]
z[:] = 0
print(y,'\n')
y[0,0,0] = 7
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(y.size,y.nbytes,y.ndim,y.shape),'\n')
print(z,'\n')
print("id(y)={0}, id(z)={1}".format(id(y),id(z)),'\n')

[[[ 0  0  0]
  [ 0  0  0]]

 [[ 7  8  9]
  [10 11 12]]] 

metadata : size=12, bytes=48, dim=3, shape=(2, 2, 3) 

[[7 0 0]
 [0 0 0]] 

id(y)=2653557786624, id(z)=2653557814256 



In [4]:
# Broadcasting (prone to bugs!)
A = np.random.randint(0,10,size=(3,4))
x = np.random.randint(10,20,size=(3,1))
b = A + x
print("    {0}    + {1}  =       {2}".format('A','x','b'))
for i in range(A.shape[0]):
    print(A[i,:],x[i],b[i])

    A    + x  =       b
[4 7 5 4] [14] [18 21 19 18]
[2 8 3 0] [18] [20 26 21 18]
[6 3 2 9] [14] [20 17 16 23]


In [5]:
# Sum vertically to obtain a row
A.sum(axis=0)

array([12, 18, 10, 13])

In [6]:
# Rank 1 array are prone to bugs

# Bad practice
x = np.random.randint(10,20,size=(3,)) # returns a rank 1 array
print(x.shape)

# Good practice
x = np.random.randint(10,20,size=(3,1)) # return a row vector
print(x.shape)

# Use assertions to debug
assert(x.shape==(3,1))

(3,)
(3, 1)
