In [1]:
import numpy as np

In [2]:
# Matrix vector product
# Note: np.multiply() and the * operator are equivalent to .* in Matlab/Octave
A = np.random.randint(0,10,size=(4,4))
x = np.random.randint(0,10,size=(4,1))
b = np.dot(A,x)

print("    {0}      {1} = {2}".format('A','x','b'))

for i in range(A.shape[1]):
    print(A[i,:],x[i],b[i])

    A      x = b
[2 6 9 8] [9] [104]
[7 1 6 5] [0] [119]
[7 8 3 1] [6] [85]
[2 4 5 9] [4] [84]
