In [1]:
import numpy as np

In [2]:
# Matrix vector product

A = np.random.randint(0,10,size=(4,4))
x = np.random.randint(0,10,size=(4,1))
b = np.dot(A,x)

print("    {0}      {1} = {2}".format('A','x','b'))

for i in range(A.shape[1]):
    print(A[i,:],x[i],b[i])

    A      x = b
[8 6 0 4] [9] [120]
[6 9 0 9] [8] [126]
[4 8 5 1] [7] [135]
[5 9 6 3] [0] [159]
