In [1]:
# Basic numpy array
import numpy as np
ar = np.zeros((2,3),dtype=np.float64)
print(ar,'\n')
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(ar.size,ar.nbytes,ar.ndim,ar.shape))

[[0. 0. 0.]
 [0. 0. 0.]] 

metadata : size=6, bytes=48, dim=2, shape=(2, 3)


In [2]:
# Reshape (creates a new view object if possible; otherwise, it copies data)
x = np.arange(1,13,1).reshape((12,1))
y = np.reshape(x,(2,2,-1))
print(y,'\n')
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(y.size,y.nbytes,y.ndim,y.shape),'\n')
x[0,0] = 1000
print(y,'\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

metadata : size=12, bytes=48, dim=3, shape=(2, 2, 3) 

[[[1000    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]] 



[Reference: numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

Note: when a shape arg is -1, the arg is automatically inferred from other args.

In the above example, a view object is created and the data is thus not copied. However, to make sure that the data is not copied while reshaping, use explicit view and then force the shape as shown [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
.

In [3]:
# View (does not copy)
z = y[1,:,:]
z[:] = 0
print(y,'\n')
y[1,0,0] = 7
print("metadata : size={0}, bytes={1}, dim={2}, shape={3}".format(y.size,y.nbytes,y.ndim,y.shape),'\n')
print(z,'\n')

[[[1000    2    3]
  [   4    5    6]]

 [[   0    0    0]
  [   0    0    0]]] 

metadata : size=12, bytes=48, dim=3, shape=(2, 2, 3) 

[[7 0 0]
 [0 0 0]] 



In [4]:
# Broadcasting (prone to bugs!)
A = np.random.randint(0,10,size=(3,4))
x = np.random.randint(10,20,size=(3,1))
b = A + x
print("    {0}    + {1}  =       {2}".format('A','x','b'))
for i in range(A.shape[0]):
    print(A[i,:],x[i],b[i])

    A    + x  =       b
[8 0 8 0] [12] [20 12 20 12]
[7 0 1 1] [16] [23 16 17 17]
[1 0 0 3] [14] [15 14 14 17]


In [5]:
# Sum vertically to obtain a row (Note use of keepdims is important to avoid bad rank 1 array)
A = np.random.randint(0,10,size=(3,4))
B = np.sum(A, axis = 0)
print(A,'\n\n',B,'  ',B.shape)
B = np.sum(A, axis = 0, keepdims = True)
print(B,' ',B.shape)

[[7 1 0 4]
 [3 1 9 4]
 [9 4 3 9]] 

 [19  6 12 17]    (4,)
[[19  6 12 17]]   (1, 4)


In [6]:
# Rank 1 array are prone to bugs

# Bad practice
x = np.random.randint(10,20,size=(3,)) # returns a rank 1 array
print(x.shape)

# Good practice
x = np.random.randint(10,20,size=(3,1)) # return a row vector
print(x.shape)

# Use assertions to debug
assert(x.shape==(3,1))

(3,)
(3, 1)


In [7]:
# np.where as an alternative to list comprehension
condition = np.random.randint(0,2,10) # boolean condition
print(condition)
head = np.array(list('H'*10))
tails = np.array(list('T'*10))
p1 = [(h if c else t) for c,h,t in zip(condition,head,tails)]
p2 = np.where(condition,head,tails)
print(p1,p2)

[0 1 1 1 1 0 0 0 0 0]
['T', 'H', 'H', 'H', 'H', 'T', 'T', 'T', 'T', 'T'] ['T' 'H' 'H' 'H' 'H' 'T' 'T' 'T' 'T' 'T']


In [8]:
# squeeze removea single-dimensional entries from the shape of an array.
# It basically returns a rank 1 array
x = np.array([[[1, 2, 3]]])
print("shape of x before squueze ",x.shape)
x = np.squeeze(x)
print("shape of x after squueze ",x.shape)

shape of x before squueze  (1, 1, 3)
shape of x after squueze  (3,)


In [9]:
# random permutation using np.random.permutation
m = 5
A = np.random.randint(0,10,size=(m,m))
x = np.random.randint(0,10,size=(m,1))
b = np.dot(A,x)
print("     {0}     * {1} = {2}".format('A','x','b'))
for i in range(A.shape[0]):
    print(A[i,:],x[i],b[i])
    
permutation = list(np.random.permutation(m))
print("\npermutation",permutation,"\n")
shuffled_A = A[:, permutation]
shuffled_x = x[permutation,:]
shuffled_b = np.dot(shuffled_A,shuffled_x)
print("     {0}     * {1} = {2}".format('A','x','b'))
for i in range(A.shape[0]):
    print(shuffled_A[i,:],shuffled_x[i],shuffled_b[i])

     A     * x = b
[8 0 7 9 7] [4] [218]
[4 1 7 8 5] [4] [179]
[4 2 2 8 9] [6] [189]
[5 3 1 5 0] [9] [83]
[0 3 5 3 8] [9] [141]

permutation [1, 0, 3, 2, 4] 

     A     * x = b
[0 8 9 7 7] [4] [218]
[1 4 8 7 5] [4] [179]
[2 4 8 2 9] [9] [189]
[3 5 5 1 0] [6] [83]
[3 0 3 5 8] [9] [141]


In [10]:
# Get index after sorting
x = np.random.randint(0,10,(3,4))
print('x = \n', x)
sortedidx = np.argsort(x,axis=1)
print('sorted index = \n',sortedidx)

x = 
 [[3 7 8 6]
 [9 5 2 3]
 [7 9 8 9]]
sorted index = 
 [[0 3 1 2]
 [2 3 1 0]
 [0 2 1 3]]


In [11]:
#Concatenate
x = np.random.randint(0,10,(2,3))
y = np.random.randint(0,10,(2,3))
print('x = \n', x)
print('y = \n', y)
z = np.concatenate((x,y),axis=0)
print('vertical(axis=0) concatenate, z = \n', z)
z = np.concatenate((x,y),axis=1)
print('horizontal(axis=1) concatenate, z = \n', z)

x = 
 [[2 9 4]
 [5 6 8]]
y = 
 [[8 9 3]
 [1 3 4]]
vertical(axis=0) concatenate, z = 
 [[2 9 4]
 [5 6 8]
 [8 9 3]
 [1 3 4]]
horizontal(axis=1) concatenate, z = 
 [[2 9 4 8 9 3]
 [5 6 8 1 3 4]]


In [12]:
# Raveling
# numpy.ravel takes a multi-dimensional array and returns its contents inside of a 1D vector.
x = np.random.randint(0,10,(2,3))
print('x = \n',x)
print('Ravelled x = ',x.ravel(),'and has shape ',x.ravel().shape)

x = 
 [[5 9 6]
 [5 0 0]]
Ravelled x =  [5 9 6 5 0 0] and has shape  (6,)
